### PR TITLE
Pass length parameter to range

### PR DESCRIPTION
**Pull request by DavidBanda**

### CODE REVIEW

**Comment by amanjiofficial** [comment]
Pass the Length parameter wherever the function `generate_token` is being called.

**Comment by DavidBanda** [comment]
Can you give me more information

**Comment by amanjiofficial** [comment]
The function `generate_token` is called in various statements in the code. We need to pass the length parameter in the function call as well. If you still have any doubt feel free to ask @DavidBanda.

**Comment by DavidBanda** [comment]
Ok,I get to work on it

**Comment by DavidBanda** [comment]
Done!

**Comment by amanjiofficial** [comment]
It will be great if you can add unit test as well. @DavidBanda

**Comment by amanjiofficial** [comment]
@DavidBanda any update?

**Comment by DavidBanda** [comment]
Sorry, I've been busy, can I use doctest?

**Comment by amanjiofficial** [comment]
I will merge this pull request and then if you want you can write unit test and create new PR

**Comment by DavidBanda** [comment]
Sounds good!

**Pull request merged**
